# Generated by Django 4.2.7 on 2023-12-04 18:32

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_blogpage_blog_title_alter_blogpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("text", wagtail.blocks.RichTextBlock()),
                    (
                        "image_carousel",
                        wagtail.blocks.ListBlock(
                            wagtail.images.blocks.ImageChooserBlock()
                        ),
                    ),
                    (
                        "bullet_list",
                        wagtail.blocks.ListBlock(wagtail.blocks.CharBlock()),
                    ),
                    (
                        "image_with_caption",
                        wagtail.blocks.ListBlock(
                            wagtail.blocks.StructBlock(
                                [
                                    (
                                        "image1",
                                        wagtail.images.blocks.ImageChooserBlock(),
                                    ),
                                    ("caption1", wagtail.blocks.CharBlock()),
                                    (
                                        "image2",
                                        wagtail.images.blocks.ImageChooserBlock(),
                                    ),
                                    ("caption2", wagtail.blocks.CharBlock()),
                                ]
                            )
                        ),
                    ),
                    (
                        "code",
                        wagtail.blocks.StructBlock(
                            [("code", wagtail.blocks.TextBlock())]
                        ),
                    ),
                    (
                        "quote",
                        wagtail.blocks.StructBlock(
                            [
                                ("quote_by", wagtail.blocks.CharBlock()),
                                ("quotes", wagtail.blocks.RichTextBlock()),
                            ]
                        ),
                    ),
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
    ]
