# Generated by Django 4.2.6 on 2023-10-18 03:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="page_title",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
